apetizer/urls.py
'''
Created on 15 janv. 2013

@author: rux
'''
from django.conf.urls import patterns, url
from apetizer.views.directory import DirectoryView
from apetizer.views.front import FrontView

handler404 = 'apetizer.views.front.handler404'
handler500 = 'apetizer.views.front.handler500'

urlpatterns = patterns( '', 
        # homepage
        url(r'^$',
            FrontView.as_view(),
            name='home',
            kwargs={'action':FrontView.default_action}),
        
        url(FrontView.get_url_regexp(r'^')+'\/$',
            FrontView.as_view(),
            kwargs={'path':'/'}),
        
        url(FrontView.get_url_regexp(r'^(?P<path>.+)\/'),
            FrontView.as_view(),
            name=FrontView.view_name,),
        
        url(r'^(?P<path>.+)\/$',
            FrontView.as_view(),
            name='home',
            kwargs={'action':FrontView.default_action}),
        
        # directory views
        url(r'^(?P<path>.+)\/directory/$',
            DirectoryView.as_view(),
            name=DirectoryView.view_name,
            kwargs={'action':DirectoryView.default_action}),
        
        url(r'^(?P<path>.+)\/query.json$',
            DirectoryView.as_view(),
            name=DirectoryView.view_name,
            kwargs={'action':'query'}),
        )

apetizer/forms/busyness.py
'''
Created on 20 nov. 2015

@author: biodigitals
'''
from apetizer.forms.base import ActionModelForm
from apetizer.models import Moderation


class ItemTranslateForm(ActionModelForm):
    slug = 'item_translate'
    title = _('Translate this item')
    class Meta:
        model = Moderation
        fields = ('cost', 'reward', 'status')

apetizer/forms/content.py
'''
Created on Feb 19, 2015

@author: nicolas
'''
import mimetypes
import os
import re

from django import forms
from django.conf import settings
from django.forms.fields import BooleanField, FloatField, DateTimeField
from django.forms.widgets import Textarea
from django.utils.html import mark_safe
from django.utils.translation import ugettext_lazy as _

import apetizer.settings as DEFAULTS
from apetizer.forms.base import ActionModelForm
from apetizer.forms.base import ActionPipeForm
from apetizer.models import Item, Translation, DATETIME_FORMATS
from apetizer.parsers.api_json import dump_json
from apetizer.utils.upload import format_file_extensions


class FormControlMixin(object):
    def set_form_control_class(self):
        for field_name in self.fields:
            self.fields[field_name].widget.attrs['class'] = 'form-control'


class BaseForm(FormControlMixin, ActionPipeForm):

    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        self.set_form_control_class()


class BaseModelForm(FormControlMixin, ActionModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseModelForm, self).__init__(*args, **kwargs)
        self.set_form_control_class()

class ItemAddForm(ActionModelForm):
    class Meta:
        model = Item
        fields = ('label', 'title', 'description','order')


class ItemPutForm(ActionModelForm):
    class Meta:
        model = Item
        fields = ('label', 'title', 'description', 'order', 
                  'latitude', 'longitude',
                  'start', 'end',
                  'related_url', 'related_cron',
                  'image', 'file',
                  'content', 'published',
                  'data', 'type', 'slug',
                  'behavior', 
                  'email', 'username', 'status',
                  'subject', 'message'
                  )



class ItemReorderForm(ActionModelForm):
    class Meta:
        model = Item
        fields = ('order',)

class ItemTranslateForm(ActionModelForm):
    slug = 'item_translate'
    title = _('Translate this item')
    class Meta:
        model = Translation
        fields = ('label', 'title', 'description')

class ItemRenameForm(ActionModelForm):
    slug = 'item_rename'
    title = _('Rename this item')
    class Meta:
        model = Translation
        fields = ('slug', 'type',)

class ItemChangeForm(ActionModelForm):
    class Meta:
        model = Item
        fields = ('behavior', 'order',)

class ItemImageForm(ActionModelForm):
    slug = 'item_image'
    title = _('Modify this item')
    class Meta:
        model = Item
        fields = ('image',)

class ItemFileForm(ActionModelForm):
    slug = 'item_file'
    title = _('Modify this item')
    class Meta:
        model = Item
        fields = ('file', 'related_cron')

class ItemCodeForm(ActionModelForm):
    slug = 'item_code'
    title = _('Code for this item')
    class Meta:
        model = Translation
        fields = ('content',)
class ItemPublishForm(ActionModelForm):
    class Meta:
        model = Item
        fields = ('behavior', 'published')

class ItemDataForm(ActionModelForm):
    slug = 'item_data'
    title = _('Code for this item')
    data = forms.CharField(max_length=4096, widget=Textarea(attrs={'cols':10,'rows':40}))
    
    class Meta:
        model = Item
        fields = ('data',)
    
class ItemRedirectForm(ActionModelForm):
    slug = 'item_redirect'
    title = _('Code for this item')
    class Meta:
        model = Translation
        fields = ('redirect_url',)

class ItemLocationForm(ActionModelForm):
    slug = 'item_location'
    title = _('Locate this item')
    
    latitude = FloatField(required=False)
    longitude = FloatField(required=False)

    class Meta:
        model = Item
        fields = ('latitude', 'longitude')

class ItemTimingForm(ActionModelForm):
    slug = 'item_timing'
    title = _('Timing for this item')
    
    start = DateTimeField(input_formats=DATETIME_FORMATS,required=False)
    end = DateTimeField(input_formats=DATETIME_FORMATS,required=False)
    
    class Meta:
        model = Item
        fields = ('start', 'end')


class ItemDeleteForm(ActionModelForm):
    slug = 'item_delete'
    title = _('Delete this item')
    do_delete = BooleanField(
        label=_(u'Yes, delete this object'),
        required=True,
    )
    class Meta:
        model = Item
        fields = tuple()


class ItemRelatedForm(ActionModelForm):
    slug = 'item_related'
    title = _('Related for this item')
    class Meta:
        model = Item
        fields = ('related_url',)



class MultiuploadWidget(forms.MultipleHiddenInput):
    def __init__(self, attrs={}):
        super(MultiuploadWidget, self).__init__(attrs)

    def render(self, name, value, attrs=None):
        widget_ = super(MultiuploadWidget, self).render(name, value, attrs)
        output = '<div id="hidden_container" style="display:none;">%s</div>' % widget_
        return mark_safe(output)


class MultiuploaderField(forms.MultiValueField):
    widget = MultiuploadWidget()

    def formfield(self, **kwargs):
        kwargs['widget'] = MultiuploadWidget
        return super(MultiuploaderField, self).formfield(**kwargs)

    def validate(self, values):
        super(MultiuploaderField, self).validate(values)

    def clean(self, values):
        super(MultiuploaderField, self).clean(values)
        return values

    def compress(self, value):
        if value:
            return value

        return None


class MultiUploadForm(forms.Form):
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        multiuploader_settings = getattr(settings, "MULTIUPLOADER_FORMS_SETTINGS", DEFAULTS.MULTIUPLOADER_FORMS_SETTINGS)

        form_type = kwargs.pop("form_type", "default")

        options = {
            'maxFileSize': multiuploader_settings[form_type]["MAX_FILE_SIZE"],
            'acceptFileTypes': format_file_extensions(multiuploader_settings[form_type]["FILE_TYPES"]),
            'maxNumberOfFiles': multiuploader_settings[form_type]["MAX_FILE_NUMBER"],
            'allowedContentTypes': list(map(str.lower, multiuploader_settings[form_type]["CONTENT_TYPES"])),
            'autoUpload': multiuploader_settings[form_type]["AUTO_UPLOAD"]
        }

        self._options = options
        self.options = dump_json(options)

        super(MultiUploadForm, self).__init__(*args, **kwargs)

        self.fields["file"].widget = forms.FileInput(attrs={'multiple': True})

    def clean_file(self):
        content = self.cleaned_data[u'file']

        filename, extension = os.path.splitext(content.name)

        if re.match(self._options['acceptFileTypes'], extension, flags=re.I) is None:
            raise forms.ValidationError('acceptFileTypes')
        
        try:
            import magic
            content_type = magic.from_buffer(content.read(1024), mime=True)
        except:
            # guess content type from extension
            content_type = mimetypes.guess_type(content.name)[0]
            
        if content_type.lower() in self._options['allowedContentTypes']:
            if content._size > self._options['maxFileSize']:
                raise forms.ValidationError("maxFileSize")
        else:
            raise forms.ValidationError("acceptFileTypes")

        return content


class MultiuploaderMultiDeleteForm(forms.Form):
    id = MultiuploaderField()

apetizer/forms/items.py
#
from apetizer.forms.base import ActionPipeForm
from django.forms import CharField

class ItemCutForm(ActionPipeForm):
    uid = CharField(label="item id to cut", max_length=185, required=True)

class ItemCopyForm(ActionPipeForm):
    uid = CharField(label="item id to copy", max_length=185, required=True)

class ItemPasteForm(ActionPipeForm):
    uid = CharField(label="item id to paste", max_length=185, required=True)

apetizer/views/api.py
'''
Created on 24 oct. 2013

@author: rux
'''
import inspect
import logging
import os.path

from django.http import HttpResponse
from django.http.response import HttpResponseRedirect

from apetizer.models import Item
from apetizer.parsers.api_json import API_json_parser, dump_json
from apetizer.views.action import ActionView


logger = logging.getLogger(__name__)


def get_class_that_defined_method(meth):
    """
    http://stackoverflow.com/questions/3589311/get-defining-class-of-unbound-method-object-in-python-3
    """
    if inspect.ismethod(meth):
        try:
            for cls in inspect.getmro(meth.im_class):
                if meth.__name__ in cls.__dict__: 
                    return cls
        except:
            for cls in inspect.getmro(meth.__self__.__class__):
                if meth.__name__ in cls.__dict__: 
                    return cls
    elif inspect.isfunction(meth):
        return getattr(inspect.getmodule(meth),
               meth.__qualname__.split('.<locals>', 1)[0].rsplit('.', 1)[0])
        
    return None

class ApiView(ActionView):
    
    class_actions = ['api', 'doc']
    class_actions_forms = {'api': [],
                           'doc': []}
    class_action_templates = {'doc':'apetizer/doc.html',
                              'api':'apetizer/api.html'}
    
    json_parser = API_json_parser

    def __init__(self, **kwargs):
        """
        Constructor. Called in the URLconf; can contain helpful extra
        keyword arguments, and other things.
        """
        # initialise the default view behavior here
        # register view_name over a global variable
        super(ApiView, self).__init__(**kwargs)
        self.__class__.get_actions()


    def render_as_json(self, request):
        """
        Tests wether the view should return json or html rendering
        """
        print 'PATH'
        print request.path
        return os.path.splitext(request.path)[1].lower() == '.json'
    
    
    def render(self, request, template_args, result_payload=None,
               result_message="OK", result_status=200, **kwargs):
        """
        Render either json or html depending on the request
        """
        #template_args['api'] = Item.objects.get_at_url('/apetizer')
        
        if result_payload == None:
            #result_payload = self.get_input_data(request)
            result_payload = {}
            result_payload['nodes'] = []
            for node in template_args['nodes']:
                #node_item_data = model_to_dict(node)
                node_data = {}
                node_data['id'] = node.id
                node_data['start'] = node.start
                node_data['title'] = node.title
                node_data['id'] = node.id
                
                result_payload['nodes'].append(node_data)
        
        if self.render_as_json(request):
            response = self.render_json(request, result_payload,
                                        result_message,
                                        result_status, **kwargs)
        else:
            response = self.render_html(request, template_args,
                                        result_message,
                                        result_status, **kwargs)
            
        return response
    
    def render_json(self, request, payload, message='ok', status=200,
                    **kwargs):
        """
        Rendering a json response from payload, message and status
        """
        if message is None:
            message = 'OK'

        json_result = {'message': message,
                       'status': status,
                       'payload': payload}

        json_string = dump_json(json_result)

        return HttpResponse(json_string, content_type='application/json')
    
    
    def process_api(self, request, user_profile, input_data, template_args,
                    **kwargs):
        
        api_action = input_data.get('action', ApiView.default_action)
        
        kwargs['action'] = api_action
        
        instances = self.get_forms_instances(api_action, user_profile, kwargs)
        
        template_args['action_forms'] = self.get_validated_forms(instances, 
                                                                 input_data, 
                                                                 api_action,
                                                                 bound_forms=len(instances))
        
        template_args['actions'] = self.actions
        
        template_args['api_action'] = api_action
        
        kwargs['action'] = 'api'
        
        return self.render(request, template_args, input_data, **kwargs)
    
    
    def process_doc(self, request, user_profile, input_data, template_args,
                    **kwargs):
        """
        Utility view witch provides a rendering of the view documentation. 
        The one you are watching.
        """
        clean_path = os.path.splitext(request.path_info)[0]

        if clean_path[-1] == '/':
            clean_path = clean_path[:-1]
        
        def get_documentation(request, **kwargs):
            """
            Return API documentation from action
            methods docstring and corresponding forms.
            """
            doc_string = '<p class="" ><h2 class="ui header" >' + self.__class__.__name__ + '</h2>'
            doc_string += self.__class__.__version__ + '</p>'
            if self.__class__.__doc__:
                doc_string += '<p class="ui sub header">' + self.__class__.__doc__.replace('\n', '<br />') + '</p>'

            #doc_string += '<h3 class="documentation-section-title">Actions</h3>'
            doc_actions = self.actions
            doc_actions.sort()
            for action in doc_actions:
                doc_string += '<div class="ui segment">'
                doc_string += '<div class="ui header" >'                
                doc_string += action
                doc_string += '<div class="sub header" >'
                doc_string += get_class_that_defined_method(getattr(self, 'process_' + action)).__name__
                doc_string += '</div>'
                doc_string += '</div>'
                
                doc_string += '</p>'
                if hasattr(self, 'process_' + action):
                    docstring = getattr(self, 'process_' + action).__doc__
                    if docstring:
                        doc_string += getattr(self, 'process_' + action).__doc__.replace('\n', '<br />')
                else:
                    doc_string += 'Not implemented<br/>'
                doc_string += '</p>'

                if action in self.actions_forms and len(self.actions_forms[action]):

                    #doc_string += '<h3 class="documentation-section-title">Forms</h3>'

                    for form in self.actions_forms[action]:
                        doc_string += '<div class="documentation-form" >'
                        doc_string += '<h4>' + form.__name__ + '</h4>'
                        if form.__doc__:
                            doc_string += '<p><i>' + form.__doc__.replace('\n', '<br />') + '</i></p>'

                        doc_string += '<ul>'
                        for field_name in form.__dict__['declared_fields']:
                            doc_string += '<li><b>' + str(field_name) + '</b> '
                            if form.__dict__['declared_fields'][field_name].required:
                                doc_string += ' (required)'
                            doc_string += '<span class="pull-right" >'
                            doc_string += form.__dict__['declared_fields'][field_name].__class__.__name__
                            doc_string += '</span><br />'
                            if form.__dict__['declared_fields'][field_name].help_text:
                                doc_string += 'Help text: '
                                doc_string += form.__dict__['declared_fields'][field_name].help_text._proxy____args[0] # ignoring proxy field
                            doc_string += '</li>'

                        doc_string += '</ul>'
                        doc_string += '</div>'
                doc_string += '</div>'

            return doc_string

        template_args['content'] = get_documentation(request, **kwargs)

        return self.render(request, template_args, input_data, **kwargs)

    

apetizer/templates/ui/add.html
{% extends "content/page.html" %}

{% block content %}
{{ block.super }}
<a class="anchor" id="bottom" style="margin-top:-234px" />
{% include "apetizer/tags/action_forms.html" %}
{% endblock %}

apetizer/templates/ui/base.html
{% extends 'content/page.html' %}

apetizer/templates/ui/code.html
{% extends 'ui/base.html' %}
{% load static content_tags %}

{% block body %}
{% endblock %}

{% block content %}
{% include 'apetizer/tags/action_forms.html' %}
{{ block.super }}
{% endblock %}

{% content_item currentNode %}

https://github.com/NextStepWebs/simplemde-markdown-editor

{% block Zextra-scripts %}

{{ block.super }}
<script type="text/javascript" src="{% static 'components/ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'components/codemirror/lib/codemirror.js' %}"></script>
<script src="{% static 'components/codemirror/mode/xml/xml.js' %}"></script>
<script src="{% static 'components/codemirror/mode/javascript/javascript.js' %}"></script>
<script src="{% static 'components/codemirror/mode/css/css.js' %}"></script>
<script src="{% static 'components/codemirror/mode/htmlmixed/htmlmixed.js' %}"></script>

<script type="text/javascript">
   $(document).ready(function(){
    
    // Iterate through all frontendadmin links
    $('a.Zfrontendadmin').each(function(){

           // Change the background color of the parent container on hover
        $(this).hover(
            function(){
                $(this).parent().addClass('frontendadmin_container_hover');
            },
            function(){
                $(this).parent().removeClass('frontendadmin_container_hover');
            }
        );
           // Load the frontendadmin form url into the parent container
        $(this).click(function(){
            $(this).parent().removeClass('frontendadmin_container_hover');
            $("#panel").show();
            $("#panel-content").load( $(this).attr('href')+' div#frontendadmin-content' );
            return false;
        });
    })
   });
   </script>
   
<script type="text/javascript" >
    
    CKEDITOR.disableAutoInline = true;
    
    function editBloc( bloc ){
        if ( !CKEDITOR.instances[bloc] )
            {
            CKEDITOR.inline( bloc );
            }
        $( 'div#'+bloc+'-toolbar' ).show();
    }
    
    function saveBloc( bloc, id ){
        
        var editor = CKEDITOR.instances[bloc];
        var form = $('form#'+bloc+'-form');
        $('input#'+id+'_content').val( editor.getData() );
        
        $.post( $(form).attr('action'), form.serialize(), function(){
            // alert('Saved '+id);
        });
        editor.destroy();
        $( 'div#'+bloc+'-toolbar' ).hide();
    }
    
    function cancelBloc( bloc, id ){
        var editor = CKEDITOR.instances[bloc];
        editor.focusManager.blur();
        editor.setData( $('input#'+id+'_content').val() );
        editor.destroy(true);
        //$( 'div#'+bloc ).html( $('input#'+id+'_content').val() );
        $( 'div#'+bloc+'-toolbar').hide();
        $( 'div#'+bloc+'-code').remove();
        $( 'button#'+bloc+'-code-btn' ).show();
    }
    
    function setSortable(){
        $('.item-list').sortable({
            /*containment: 'parent',
            zindex: 10, */
            items: '.item-list-element',
            handle: 'a:first',
            update: function() {
                $(this).find('.item-list-element').each(function(i) {
                    if ($(this).find('input[id$=name]').val()) {
                        $(this).find('input[id$=order]').val(i+1);
                    }
                });
            }
        });
        $('.item-list').disableSelection();
        $('.item-list-element').css('cursor', 'move');
        $('.item-list-element').find('input[id$=order]').parent('div').hide();
    };
    
    function codeBloc( bloc, id ){
        
        var ckeditor = CKEDITOR.instances[bloc];
        ckeditor.focusManager.blur();
        
        // edit area
        var editArea = $('<div id="'+bloc+'-code" ><textarea id="'+bloc+'-code-area" name="code" style="height:128px" ></textarea><div>');
        editArea.val( ckeditor.getData() );
        
        // add textarea
        $( 'div#'+bloc+'-toolbar' ).prepend( editArea );
        
        // init codemirror
        var codeEditor = CodeMirror.fromTextArea( document.getElementById( bloc+"-code-area" ), 
                {
                mode: "text/html", 
                tabMode: "indent", 
                lineNumbers:true, 
                onBlur: function(cm){ ckeditor.setData( cm.getValue() ); },
                });
        
        ckeditor.on('blur', function() { codeEditor.setValue( ckeditor.getData() ) });
        
        // hide code btn
        $( 'button#'+bloc+'-code-btn' ).hide();
    }
    
</script>
{% endblock %}

apetizer/templates/ui/data.html
{% extends 'ui/change.html' %}

apetizer/templates/ui/file.html
{% extends 'content/page.html' %}


{% block body %}
{% include 'apetizer/tags/action_forms.html' %}
{% endblock %}

{% block page_article %}
{% if currentNode.file %}
<div class="ui sixteen wide column vertical segment" style="padding:0px;margin:0px">
    {% if currentNode.file.name|slice:":8" == 'resource' %}
    <iframe id="_apetizer_code" name="_apetizer_code" src="/notebooks/{{ currentNode.file.name }}" width="100%" height="800" border="0" style="border:0px solid gray;" ></iframe>
    {% elif currentNode.file.name|slice:":6" == 'medias' %}
    <iframe id="_apetizer_code" name="_apetizer_code" src="/notebooks/{{ currentNode.file.name }}" width="100%" height="800" border="0" style="border:0px solid gray;" ></iframe>
    {% elif currentNode.file.name|slice:":6" == 'media' %}
    <iframe id="_apetizer_code" name="_apetizer_code" src="/notebooks/{{ currentNode.file.name }}" width="100%" height="800" border="0" style="border:0px solid gray;" ></iframe>
    {% else %}
    <iframe id="_apetizer_code" name="_apetizer_code" src="{{ currentNode.file.url }}" width="100%" height="800" border="0" style="border:0px solid gray;" ></iframe>
    {% endif %}
</div>
{% endif %}
{{ block.super }}
{% endblock %}


{% block Zpage_container %}
{% if currentNode.related_url and 'hackpad' in currentNode.related_url %}
    <script src="{{ currentNode.related_url }}.js"></script><noscript>
    <div>View <a href="{{ currentNode.related_url }}">{{ currentNode.title }}</a> on Hackpad.</div>
    </noscript>
{% elif currentNode.related_url and 'twitter' in currentNode.related_url %}
    <div class="col-md-12 text-center">
        <form action="" method="GET" >
            <input name="keyword" value="{{ request.POST.keyword }}" type="text" placeholder="keyword" />
        </form>
    </div>
{% elif currentNode.related_url and 'meetup' in currentNode.related_url %}

{% elif currentNode.related_url %}
    <div class="ui sixteen wide column vertical segment" style="padding:0px;margin:0px">
    <iframe src="{{ currentNode.related_url }}" width="100%" height="720" border="0" style="border:1px solid gray;" ></iframe>
    </div>
{% else %}

{% endif %}
{{ block.super }}
{% endblock %}

apetizer/templates/ui/image.html
{% extends 'content/page.html' %}

{% block body %}
{% include 'apetizer/tags/action_forms.html' %}
{% endblock %}

{% block page_article %}
{% if currentNode.image %}
    <div class="ui sixteen wide column vertical segment" style="padding:0px;margin:0px">
    <iframe src="{{ currentNode.image.url }}" width="100%" height="720" border="0" style="border:1px solid gray;" ></iframe>
    </div>
{% else %}
{% endif %}
{{ block.super }}
{% endblock %}

apetizer/templates/ui/location.html
{% extends "ui/change.html" %}
{% load i18n leaflet_tags %}

apetizer/templates/ui/redirect.html
{% extends 'ui/sitemap.html' %}


{% block body %}
{% include 'ui/tags/form.html' %}
{% endblock %}

apetizer/templates/ui/translate.html
{% extends "ui/base.html" %}
{% load i18n %}

{% block body %}
{% include 'apetizer/tags/action_forms.html' %}
{% endblock %}

{% block ui-form %}
{% endblock %}

apetizer/templates/ui/upload.html
{% extends "ui/base.html" %}
{% load i18n multiuploader staticfiles verbatim %}

{% block Zcontent %}
<div class="ui grid">
    {% for ufile in currentNode.medias.all %}
    <div class="five wide column">
        <div class="ui segment image" data-ref-id="{{ ufile.id }}" >
            <img src="{{ ufile.file.url }}" />
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}


{% block ui-form %}
{{ block.super }}
{% endblock %}
{% include "ui/tags/upload.html" %}

{% block extra-styles %}

{{ block.super }}
<link rel="stylesheet" href="{% static "components/multiuploader/styles/jquery-ui.css" %}" id="theme">
<link rel="stylesheet" href="{% static "components/multiuploader/styles/jquery.fileupload-ui.css" %}">
{% endblock %}

{% block extra-scripts %}
{{ block.super }}

{% comment %}
<script src="{% static "components/multiuploader/scripts/jquery.tmpl.min.js" %}"></script>
<script src="{% static "components/multiuploader/scripts/jquery.iframe-transport.js" %}"></script>
<script src="https://code.jquery.com/jquery-1.11.2.min.js" ></script>
<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js" ></script>

<script src="https://raw.githubusercontent.com/blueimp/jQuery-File-Upload/master/js/jquery.fileupload.js"></script>
<script src="https://raw.githubusercontent.com/blueimp/jQuery-File-Upload/master/js/jquery.fileupload-ui.js"></script>
{% endcomment %}


<script src="{% static "components/multiuploader/scripts/jquery.min.js" %}"></script>
<script src="{% static "components/multiuploader/scripts/jquery-ui.min.js" %}"></script>
<script src="{% static "components/multiuploader/scripts/jquery.tmpl.min.js" %}"></script>
<script src="{% static "components/multiuploader/scripts/jquery.iframe-transport.js" %}"></script>
<script src="{% static "components/multiuploader/scripts/jquery.fileupload.js" %}"></script>
<script src="{% static "components/multiuploader/scripts/jquery.fileupload-ui.js" %}"></script>

<script type="text/javascript" src="{% static "components/multiuploader/scripts/collectfiles.js" %}"></script>

<script type="text/javascript">
    var translation = {
        {% comment %}Translators: Start and Stop uploading buttons captions {% endcomment %}
        "Start": "{% trans "Start" %}",
        "Stop": "{% trans "Stop" %}",
        {% comment %}Translators: Errors and its descriptions {% endcomment %}
        "Error": "{% trans "Error" %}",
        "File is too big": "{% trans "File is too big" %}",
        "File is too small": "{% trans "File is too small" %}",
        "Filetype not allowed": "{% trans "Filetype not allowed" %}",
        "Max number of files exceeded": "{% trans "Max number of files exceeded" %}",
        "File exceeds upload_max_filesize": "{% trans "File exceeds maximum upload limit" %}",
        "File exceeds MAX_FILE_SIZE (HTML form directive)": "{% trans "File exceeds maximum size of upload" %}",
        "File is too small": "{% trans "File is too small" %}",
        "File was only partially uploaded": "{% trans "File was only partially uploaded" %}",
        "No File was uploaded": "{% trans "No File was uploaded" %}",
        "Missing a temporary folder": "{% trans "Missing a temporary folder" %}",
        "Failed to write file to disk": "{% trans "Failed to write file to disk" %}",
        "File upload stopped by extension": "{% trans "File upload stopped by extension" %}",
        "Empty file upload result": "{% trans "Empty file upload result" %}"
    };
</script>

<script type="text/javascript">
	
	$(document).ready(function(){
		
		
	    setup_widget(jQuery);
	    setup_ui(jQuery);
	
	    (function ($) {
	        'use strict';
	
	        var multiuploaderSelector = '#id_file';
			
	        var opts = {{ multiuploader_form.options|safe }};
	
	        // Making new RegExp from django string
	        //opts['acceptFileTypes'] = new RegExp('/\/.+$/i');
	        //opts['acceptFileTypes'] = new RegExp("^.*\\." + 'jpg|png' + "[^.]+$", "i"),
	        opts['acceptFileTypes'] = new RegExp(opts['acceptFileTypes'], 'i');
	        opts['maxNumberOfFiles'] = opts['maxNumberOfFiles'];
	
	        $(multiuploaderSelector).fileupload(opts);
	
	        // Load existing files:
	        $.getJSON($(multiuploaderSelector + ' form').prop('action'), function (files) {
	            var fu = $(multiuploaderSelector).data('fileupload');
	            fu._adjustMaxNumberOfFiles(-files.length);
	            fu._renderDownload(files)
	                    .appendTo($(multiuploaderSelector + ' .files'))
	                    .fadeIn(function () {
	                        // Fix for IE7 and lower:
	                        $(this).show();
	                    });
	        });
	
	        // Open download dialogs via iframes,
	        // to prevent aborting current uploads:
	
	        $(multiuploaderSelector + ' .files a:not([target^=_blank])').live('click', function (e) {
	            e.preventDefault();
	            $('<iframe style="display:none;"></iframe>')
	                    .prop('src', this.href)
	                    .appendTo('body');
	        });
			
	        // Making multiuploader visible
	        $(multiuploaderSelector).removeAttr("style");
	
	    })(jQuery);
	    
	    setup_filecollector(jQuery,"id_file","input[name=_edit]", true);
    
	});
</script>

{% endblock %}